Use Primitive#upload instead of copy/paste its code
mavoweb/plugins pull request #71
Opened 2020-07-12 08:00 UTC by DmitrySharabin

I just want to say that it's OK if we won't merge this PR since it has to deal with some aspects of properties, like an attribute and a property value (see the comments in the code).

If we decide to leave the previously merged version, it might be a good idea to use line 121 from this PR and send a separate PR with it. What do you think?

2020-11-25 09:08 UTC, DmitrySharabin commented
@LeaVerou Hey Lea! 👋🏻
Will you please have a look at this PR? I have an open Gestalt because ot it. :)

2020-11-25 17:25 UTC, LeaVerou requested changes
I added some comments, though since this is a clear improvement over the previous code I'm tempted to merge as-is. Up to you!

2020-11-25 17:25 UTC, LeaVerou commented on markdown/mavo-markdown.js
> +						t.setSelectionRange(cursorPosition, cursorPosition + placeholder.length);
What about when there's a selection?
What about after the upload?

2020-11-25 17:25 UTC, LeaVerou commented on markdown/mavo-markdown.js
>  				const item = Array.from(evt.clipboardData.items).find(item => item.kind == "file" && item.type.indexOf("image/") === 0);
This also seems like it should live in one place and not be repeated everywhere uploads via paste are allowed, but that's minor.

2020-11-25 17:25 UTC, LeaVerou commented on markdown/mavo-markdown.js
> +						const placeholder = `![${this.mavo._("uploading")}...]()`;
What happens if a user tries to save while an image is uploading?
Github disables the submit button until the upload finishes. Do we want to do something similar? Do we want to perhaps introduce a confirmation?

2020-11-25 17:40 UTC, LeaVerou commented
Also, do note that simply replacing the entire text drops your undo stack. There are workarounds, but not for all browsers. 

See

https://stackoverflow.com/questions/19814465/is-it-possible-to-insert-text-in-textarea-and-update-undo-redo-queuehttps://stackoverflow.com/questions/44471699/how-to-make-undo-work-in-an-html-textarea-after-setting-the-value

and many others

2020-11-26 06:48 UTC, DmitrySharabin commented
Thank you, Lea, for all your comments. I learn a lot from you. I'll work through them and will make some improvements.

2020-11-30 12:43 UTC, DmitrySharabin commented
As I mentioned in #76, I'm going to close this PR with a pure heart. I learned a lot from it. :)

2020-11-30 12:43 UTC, closed without merging